server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: team04-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/elice_team04?serverTimezone=UTC&characterEncoding=UTF-8